create extension if not exists pgcrypto;

create table if not exists public.deployment_jobs (id uuid primary key default gen_random_uuid(), protocol_id uuid, scaffold_job_id uuid, deploy_status text not null default 'deploy_queued', input_payload jsonb not null default '{}'::jsonb, deployment_plan jsonb not null default '{}'::jsonb, output_summary jsonb not null default '{}'::jsonb, error_message text, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.deployment_configs (id uuid primary key default gen_random_uuid(), deployment_job_id uuid references public.deployment_jobs(id) on delete cascade, config_key text not null, config_type text not null default 'environment', is_required boolean not null default true, is_secret boolean not null default true, config_status text not null default 'pending', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(deployment_job_id, config_key));
create table if not exists public.deployment_logs (id uuid primary key default gen_random_uuid(), deployment_job_id uuid references public.deployment_jobs(id) on delete cascade, log_level text not null default 'info', step_name text, message text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.github_repositories (id uuid primary key default gen_random_uuid(), deployment_job_id uuid references public.deployment_jobs(id) on delete set null, repository_name text not null, repository_url text, branch_name text, commit_sha text, status text not null default 'pending', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.skill_registry (id uuid primary key default gen_random_uuid(), automation_key text not null, skill_name text not null, skill_path text not null, skill_version text, skill_hash text, commit_sha text, status text not null default 'registered_pending_activation', required_configs jsonb not null default '[]'::jsonb, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.agent_registry (id uuid primary key default gen_random_uuid(), automation_key text not null, agent_name text not null, agent_type text not null, agent_definition_path text, status text not null default 'registered_pending_activation', capabilities jsonb not null default '[]'::jsonb, skills jsonb not null default '[]'::jsonb, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.automation_registry (id uuid primary key default gen_random_uuid(), automation_key text not null unique, automation_name text, automation_status text not null default 'configured', health_status text not null default 'unknown', version text, repository_url text, commit_sha text, runtime_config jsonb not null default '{}'::jsonb, activated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.runtime_events (id uuid primary key default gen_random_uuid(), automation_key text, event_type text not null, event_payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
